server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/login-api
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: info